project:
  type: website

website:
  title: "*EarlyPrint* rhymes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar:
    style: "docked"
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



