project:
  type: website

website:
  title: "*EarlyPrint* rhymes"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    code-fold: true
    toc: true
    toc-title: "Contents"
    toc-depth: 6



